### ISSUE TITLE
How to collect data? 

### ISSUE THREAD

**Issue by MiuGod0126** [TBC-TJU/MetaBCI#1]
Hello ,thank you for a great job!!！ I'm a newbie in this area, is there any cheap equipment to collect data set for BCI ?

**Comment by lwlBCI** [comment]
> Hello ,thank you for a great job!!！ I'm a newbie in this area, is there any cheap equipment to collect data set for BCI ?

If you don't have enough funds and want to take into account the cost-effectiveness, I recommend you to buy Emotiv EPOC+

**Comment by MiuGod0126** [comment]
> > Hello ,thank you for a great job!!！ I'm a newbie in this area, is there any cheap equipment to collect data set for BCI ?
> 
> If you don't have enough funds and want to take into account the cost-effectiveness, I recommend you to buy Emotiv EPOC+

Ok, thanks for your valuable advice! Maybe I should start learning from public datasets first.
