### ISSUE TITLE
解码算法中的很多方法函数文件不存在，但是代码仍然可以运行，请问是什么原因？

### ISSUE THREAD

**Issue by Sungden** [TBC-TJU/MetaBCI#50]
<img width="541" alt="image" src="https://github.com/TBC-TJU/MetaBCI/assets/54644867/2fed59ee-d5ac-4654-b047-17b07b456f06">

**Comment by ch-MEIJIE** [comment]
Hi
感谢你的提问，我没有复现出相同的问题。如果在vscode中打开你截图中的文件，在FBTRCA（你画红线的位置）右键"Go to Definition"可以跳转到位于/metabci/brainda/algorithm/decomposition/cca下的FBTRCA类。
希望能够帮到你，如有问题请继续讨论。

**Comment by Sungden** [comment]
谢谢
