### ISSUE TITLE
MetaBCI支持LSL吗

### ISSUE THREAD

**Issue by Morgendfl** [TBC-TJU/MetaBCI#60]
如果使用其他品牌的脑电设备（其软件支持LSL），能否与MetaBCI进行实时数据传输呢？MetaBCI是否支持LSL呢？
希望能得到回复，感谢！

**Comment by ch-MEIJIE** [comment]
你好，感谢你对MetaBCI的关注，我们在brainflow中实现了一个与LSL的接口，具体请参看 [https://github.com/TBC-TJU/MetaBCI/blob/master/metabci/brainflow/amplifiers.py](LSLapps())类。
但是这个功能仅仅做了简单测试，如果有问题请再联系我们。
