### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by Xinen-hardwork** [TBC-TJU/MetaBCI#70]
![install issue](https://github.com/TBC-TJU/MetaBCI/assets/156279389/094ac2ca-af6b-4928-aa46-70ef67f9f14b)
您好，很感谢你们做出MetaBCI这么好用的开源平台，可是我在安装的过程中一直遇到下面问题，希望您可以帮忙解决一下，谢谢！！！
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\29221\AppData\Local\Temp\pip-install-48_f4m0s\gevent_5ba2c49fd3b04bd79bd7e2f234710595\setup.py", line 95
          print 'Linking %s to %s' % (path_to_build_core_so, path_to_core_so)
                ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ch-MEIJIE** [comment]
您好，感谢您对MetaBCI的兴趣。
（1）请问您的虚拟环境的Python版本是？建议使用Python 3.8。
（2）看起来您在使用Conda管理环境，您可尝试使用conda首先安装这个失败的包，然后再尝试安装MetaBCI。
（3）如果您有后续问题，请继续交流。

**Comment by Xinen-hardwork** [comment]
您好，十分感谢您的回复，在您的建议下我目前是安装好了metabci这个十分创新的工具，再次对您创造出MetaBCI这种优秀的开源工具表示感谢，后面使用过程中如果出现疑惑，还想您不吝赐教。

**Comment by ch-MEIJIE** [comment]
再次感谢您的关注，我们是否可以关闭这个issue了？

**Comment by Xinen-hardwork** [comment]
当然可以呀，十分感谢您热心的回复！！
