### ISSUE TITLE
How can I use my own local SSVEP dataset to import this framework for experimentation?

### ISSUE THREAD

**Issue by Axeliar** [TBC-TJU/MetaBCI#77]
1. How can I use my own local SSVEP dataset to import this framework for experimentation?
2. How to specify the local download location for datasets provided by META BCI, such as BETA datasets, to avoid duplicate downloads of datasets？

**Comment by ch-MEIJIE** [comment]
Thanks for your attention on MetaBCI!

1. For using your own local SSVEP dataset in our MetaBCI framework, you should implement a new dataset class. Please refer to this example [Dataset](https://github.com/TBC-TJU/MetaBCI/blob/master/demos/brainflow_demos/datasets.py).
2. The datasets downloaded online are saved in  "\~/mne_data", and each of them had a unique identifier (passing `dataset_code` when initialing the dataset class). We also have a `force_update` parameter when initialing the dataset but its default is False. This means if MetaBCI found the dataset's unique identifier in the "\~/mne_data", it wouldn't download the dataset again from the website, unless the `force_update` was set to True.

If you have any other questions, plz contact us.
