### ISSUE TITLE
请问中文文档会提供吗？

### ISSUE THREAD

**Issue by cncowboy** [TBC-TJU/MetaBCI#9]

**Comment by Axeliar** [comment]
README里有提到，给项目组发邮件，说明自己的机构名和姓名，会提供中文文档的。

**Comment by ch-MEIJIE** [comment]
请发送邮件到：TBC_TJU_2022@163.com，并附上您的机构（课题组、学校）名、负责人姓名等信息。收到邮件后我们会将中文说明文档回复至您的邮箱。
Thanks for your attention on MetaBCI, shall we close this issue?

**Comment by cncowboy** [comment]
好的，谢谢！
